// Fallback list of countries with dial codes
// Used when API is unavailable
export interface CountryWithDialCode {
  code: string;
  name: string;
  dialCode: string;
}

// Mapping of country codes to dial codes
const COUNTRY_TO_DIAL_CODE: Record<string, string> = {
  'US': '+1', 'CA': '+1', 'RU': '+7', 'KZ': '+7', 'FR': '+33', 'DE': '+49',
  'GB': '+44', 'IT': '+39', 'ES': '+34', 'AU': '+61', 'JP': '+81', 'CN': '+86',
  'IN': '+91', 'PK': '+92', 'BR': '+55', 'MX': '+52', 'AR': '+54', 'PL': '+48',
  'NL': '+31', 'BE': '+32', 'CH': '+41', 'AT': '+43', 'SE': '+46', 'NO': '+47',
  'DK': '+45', 'FI': '+358', 'TR': '+90', 'KR': '+82', 'SG': '+65', 'TH': '+66',
  'ID': '+62', 'MY': '+60', 'PH': '+63', 'VN': '+84', 'UA': '+380', 'BY': '+375',
  'UZ': '+998', 'GE': '+995', 'AM': '+374', 'AZ': '+994', 'IL': '+972', 'SA': '+966',
  'AE': '+971', 'EG': '+20', 'ZA': '+27', 'NG': '+234', 'KE': '+254', 'MA': '+212',
  'TN': '+216', 'DZ': '+213', 'LY': '+218', 'SD': '+249', 'ET': '+251', 'GH': '+233',
  'CI': '+225', 'SN': '+221', 'ML': '+223', 'BF': '+226', 'NE': '+227', 'TD': '+235',
  'MG': '+261', 'UG': '+256', 'TZ': '+255', 'ZW': '+263', 'ZM': '+260', 'BW': '+267',
  'NA': '+264', 'SZ': '+268', 'LS': '+266', 'MW': '+265', 'MZ': '+258', 'AO': '+244',
  'CG': '+242', 'CD': '+243', 'CF': '+236', 'CM': '+237', 'GA': '+241', 'GQ': '+240',
  'ST': '+239', 'RW': '+250', 'BI': '+257', 'DJ': '+253', 'SO': '+252', 'ER': '+291',
  'KM': '+269', 'MU': '+230', 'SC': '+248', 'CV': '+238', 'GW': '+245', 'GN': '+224',
  'SL': '+232', 'LR': '+231', 'TG': '+228', 'BJ': '+229', 'GM': '+220', 'IE': '+353',
  'PT': '+351', 'GR': '+30', 'CY': '+357', 'MT': '+356', 'LU': '+352', 'IS': '+354',
  'EE': '+372', 'LV': '+371', 'LT': '+370', 'CZ': '+420', 'SK': '+421', 'HU': '+36',
  'RO': '+40', 'BG': '+359', 'HR': '+385', 'SI': '+386', 'BA': '+387', 'RS': '+381',
  'ME': '+382', 'MK': '+389', 'AL': '+355', 'XK': '+383', 'MD': '+373', 'AF': '+93',
  'BD': '+880', 'BT': '+975', 'KH': '+855', 'LK': '+94', 'MV': '+960', 'MM': '+95',
  'NP': '+977', 'TL': '+670', 'BN': '+673', 'FJ': '+679', 'PG': '+675', 'SB': '+677',
  'VU': '+678', 'NC': '+687', 'PF': '+689', 'WS': '+685', 'TO': '+676', 'TV': '+688',
  'KI': '+686', 'NR': '+674', 'PW': '+680', 'FM': '+691', 'MH': '+692', 'IQ': '+964',
  'IR': '+98', 'JO': '+962', 'KW': '+965', 'LB': '+961', 'OM': '+968', 'PS': '+970',
  'QA': '+974', 'SY': '+963', 'YE': '+967', 'BH': '+973',
  'CL': '+56', 'CO': '+57', 'CR': '+506', 'CU': '+53', 'DO': '+1', 'EC': '+593',
  'SV': '+503', 'GT': '+502', 'HN': '+504', 'JM': '+1', 'NI': '+505', 'PA': '+507',
  'PY': '+595', 'PE': '+51', 'PR': '+1', 'TT': '+1', 'UY': '+598', 'VE': '+58',
  'BO': '+591', 'GY': '+592', 'SR': '+597', 'FK': '+500', 'GF': '+594', 'GP': '+590',
  'MQ': '+596', 'PM': '+508', 'BL': '+590', 'MF': '+590', 'CW': '+599', 'SX': '+1',
  'BQ': '+599', 'AW': '+297', 'AG': '+1', 'BS': '+1', 'BB': '+1', 'DM': '+1',
  'GD': '+1', 'KN': '+1', 'LC': '+1', 'VC': '+1', 'TC': '+1', 'VG': '+1',
  'VI': '+1', 'AI': '+1', 'BM': '+1', 'KY': '+1', 'MS': '+1',
  'SH': '+290', 'GS': '+500', 'TF': '+262', 'AD': '+376', 'LI': '+423', 'MC': '+377',
  'SM': '+378', 'VA': '+39', 'AX': '+358', 'FO': '+298', 'GL': '+299', 'SJ': '+47',
  'IM': '+44', 'JE': '+44', 'GG': '+44', 'GI': '+350', 'MO': '+853',
  'HK': '+852', 'TW': '+886', 'KP': '+850', 'MN': '+976', 'LA': '+856',
  'NZ': '+64', 'AS': '+1', 'GU': '+1', 'MP': '+1', 'UM': '+1', 'AQ': '+672',
  'BV': '+47', 'HM': '+672', 'CC': '+61', 'CX': '+61', 'NF': '+672', 'TK': '+690',
  'NU': '+683', 'PN': '+872', 'WF': '+681', 'EH': '+212', 'IO': '+246', 'RE': '+262',
  'YT': '+262', 'TJ': '+992', 'TM': '+993', 'KG': '+996', 'HT': '+509'
};

// Full list of all countries (ISO 3166-1 alpha-2)
const ALL_COUNTRIES: Array<{ code: string; name: string }> = [
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algeria" },
  { code: "AS", name: "American Samoa" },
  { code: "AD", name: "Andorra" },
  { code: "AO", name: "Angola" },
  { code: "AI", name: "Anguilla" },
  { code: "AQ", name: "Antarctica" },
  { code: "AG", name: "Antigua and Barbuda" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AW", name: "Aruba" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Austria" },
  { code: "AZ", name: "Azerbaijan" },
  { code: "BS", name: "Bahamas" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BB", name: "Barbados" },
  { code: "BY", name: "Belarus" },
  { code: "BE", name: "Belgium" },
  { code: "BZ", name: "Belize" },
  { code: "BJ", name: "Benin" },
  { code: "BM", name: "Bermuda" },
  { code: "BT", name: "Bhutan" },
  { code: "BO", name: "Bolivia" },
  { code: "BA", name: "Bosnia and Herzegovina" },
  { code: "BW", name: "Botswana" },
  { code: "BV", name: "Bouvet Island" },
  { code: "BR", name: "Brazil" },
  { code: "IO", name: "British Indian Ocean Territory" },
  { code: "BN", name: "Brunei Darussalam" },
  { code: "BG", name: "Bulgaria" },
  { code: "BF", name: "Burkina Faso" },
  { code: "BI", name: "Burundi" },
  { code: "KH", name: "Cambodia" },
  { code: "CM", name: "Cameroon" },
  { code: "CA", name: "Canada" },
  { code: "CV", name: "Cape Verde" },
  { code: "KY", name: "Cayman Islands" },
  { code: "CF", name: "Central African Republic" },
  { code: "TD", name: "Chad" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "China" },
  { code: "CX", name: "Christmas Island" },
  { code: "CC", name: "Cocos (Keeling) Islands" },
  { code: "CO", name: "Colombia" },
  { code: "KM", name: "Comoros" },
  { code: "CG", name: "Congo" },
  { code: "CD", name: "Congo, The Democratic Republic of the" },
  { code: "CK", name: "Cook Islands" },
  { code: "CR", name: "Costa Rica" },
  { code: "CI", name: "Cote D'Ivoire" },
  { code: "HR", name: "Croatia" },
  { code: "CU", name: "Cuba" },
  { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czech Republic" },
  { code: "DK", name: "Denmark" },
  { code: "DJ", name: "Djibouti" },
  { code: "DM", name: "Dominica" },
  { code: "DO", name: "Dominican Republic" },
  { code: "EC", name: "Ecuador" },
  { code: "EG", name: "Egypt" },
  { code: "SV", name: "El Salvador" },
  { code: "GQ", name: "Equatorial Guinea" },
  { code: "ER", name: "Eritrea" },
  { code: "EE", name: "Estonia" },
  { code: "ET", name: "Ethiopia" },
  { code: "FK", name: "Falkland Islands (Malvinas)" },
  { code: "FO", name: "Faroe Islands" },
  { code: "FJ", name: "Fiji" },
  { code: "FI", name: "Finland" },
  { code: "FR", name: "France" },
  { code: "GF", name: "French Guiana" },
  { code: "PF", name: "French Polynesia" },
  { code: "TF", name: "French Southern Territories" },
  { code: "GA", name: "Gabon" },
  { code: "GM", name: "Gambia" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Germany" },
  { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" },
  { code: "GR", name: "Greece" },
  { code: "GL", name: "Greenland" },
  { code: "GD", name: "Grenada" },
  { code: "GP", name: "Guadeloupe" },
  { code: "GU", name: "Guam" },
  { code: "GT", name: "Guatemala" },
  { code: "GG", name: "Guernsey" },
  { code: "GN", name: "Guinea" },
  { code: "GW", name: "Guinea-Bissau" },
  { code: "GY", name: "Guyana" },
  { code: "HT", name: "Haiti" },
  { code: "HM", name: "Heard Island and Mcdonald Islands" },
  { code: "VA", name: "Holy See (Vatican City State)" },
  { code: "HN", name: "Honduras" },
  { code: "HK", name: "Hong Kong" },
  { code: "HU", name: "Hungary" },
  { code: "IS", name: "Iceland" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran, Islamic Republic of" },
  { code: "IQ", name: "Iraq" },
  { code: "IE", name: "Ireland" },
  { code: "IM", name: "Isle of Man" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italy" },
  { code: "JM", name: "Jamaica" },
  { code: "JP", name: "Japan" },
  { code: "JE", name: "Jersey" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kazakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KI", name: "Kiribati" },
  { code: "KP", name: "Korea, Democratic People's Republic of" },
  { code: "KR", name: "Korea, Republic of" },
  { code: "KW", name: "Kuwait" },
  { code: "KG", name: "Kyrgyzstan" },
  { code: "LA", name: "Lao People's Democratic Republic" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Lebanon" },
  { code: "LS", name: "Lesotho" },
  { code: "LR", name: "Liberia" },
  { code: "LY", name: "Libyan Arab Jamahiriya" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Lithuania" },
  { code: "LU", name: "Luxembourg" },
  { code: "MO", name: "Macao" },
  { code: "MK", name: "Macedonia, The Former Yugoslav Republic of" },
  { code: "MG", name: "Madagascar" },
  { code: "MW", name: "Malawi" },
  { code: "MY", name: "Malaysia" },
  { code: "MV", name: "Maldives" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MH", name: "Marshall Islands" },
  { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" },
  { code: "MU", name: "Mauritius" },
  { code: "YT", name: "Mayotte" },
  { code: "MX", name: "Mexico" },
  { code: "FM", name: "Micronesia, Federated States of" },
  { code: "MD", name: "Moldova, Republic of" },
  { code: "MC", name: "Monaco" },
  { code: "MN", name: "Mongolia" },
  { code: "ME", name: "Montenegro" },
  { code: "MS", name: "Montserrat" },
  { code: "MA", name: "Morocco" },
  { code: "MZ", name: "Mozambique" },
  { code: "MM", name: "Myanmar" },
  { code: "NA", name: "Namibia" },
  { code: "NR", name: "Nauru" },
  { code: "NP", name: "Nepal" },
  { code: "NL", name: "Netherlands" },
  { code: "AN", name: "Netherlands Antilles" },
  { code: "NC", name: "New Caledonia" },
  { code: "NZ", name: "New Zealand" },
  { code: "NI", name: "Nicaragua" },
  { code: "NE", name: "Niger" },
  { code: "NG", name: "Nigeria" },
  { code: "NU", name: "Niue" },
  { code: "NF", name: "Norfolk Island" },
  { code: "MP", name: "Northern Mariana Islands" },
  { code: "NO", name: "Norway" },
  { code: "OM", name: "Oman" },
  { code: "PK", name: "Pakistan" },
  { code: "PW", name: "Palau" },
  { code: "PS", name: "Palestinian Territory, Occupied" },
  { code: "PA", name: "Panama" },
  { code: "PG", name: "Papua New Guinea" },
  { code: "PY", name: "Paraguay" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Philippines" },
  { code: "PN", name: "Pitcairn" },
  { code: "PL", name: "Poland" },
  { code: "PT", name: "Portugal" },
  { code: "PR", name: "Puerto Rico" },
  { code: "QA", name: "Qatar" },
  { code: "RE", name: "Reunion" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russian Federation" },
  { code: "RW", name: "Rwanda" },
  { code: "SH", name: "Saint Helena" },
  { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "LC", name: "Saint Lucia" },
  { code: "PM", name: "Saint Pierre and Miquelon" },
  { code: "VC", name: "Saint Vincent and the Grenadines" },
  { code: "WS", name: "Samoa" },
  { code: "SM", name: "San Marino" },
  { code: "ST", name: "Sao Tome and Principe" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "SN", name: "Senegal" },
  { code: "RS", name: "Serbia" },
  { code: "SC", name: "Seychelles" },
  { code: "SL", name: "Sierra Leone" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SB", name: "Solomon Islands" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "South Africa" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands" },
  { code: "ES", name: "Spain" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SD", name: "Sudan" },
  { code: "SR", name: "Suriname" },
  { code: "SJ", name: "Svalbard and Jan Mayen" },
  { code: "SZ", name: "Swaziland" },
  { code: "SE", name: "Sweden" },
  { code: "CH", name: "Switzerland" },
  { code: "SY", name: "Syrian Arab Republic" },
  { code: "TW", name: "Taiwan, Province of China" },
  { code: "TJ", name: "Tajikistan" },
  { code: "TZ", name: "Tanzania, United Republic of" },
  { code: "TH", name: "Thailand" },
  { code: "TL", name: "Timor-Leste" },
  { code: "TG", name: "Togo" },
  { code: "TK", name: "Tokelau" },
  { code: "TO", name: "Tonga" },
  { code: "TT", name: "Trinidad and Tobago" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Turkey" },
  { code: "TM", name: "Turkmenistan" },
  { code: "TC", name: "Turks and Caicos Islands" },
  { code: "TV", name: "Tuvalu" },
  { code: "UG", name: "Uganda" },
  { code: "UA", name: "Ukraine" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "GB", name: "United Kingdom" },
  { code: "US", name: "United States" },
  { code: "UM", name: "United States Minor Outlying Islands" },
  { code: "UY", name: "Uruguay" },
  { code: "UZ", name: "Uzbekistan" },
  { code: "VU", name: "Vanuatu" },
  { code: "VE", name: "Venezuela" },
  { code: "VN", name: "Vietnam" },
  { code: "VG", name: "Virgin Islands, British" },
  { code: "VI", name: "Virgin Islands, U.S." },
  { code: "WF", name: "Wallis and Futuna" },
  { code: "EH", name: "Western Sahara" },
  { code: "YE", name: "Yemen" },
  { code: "ZM", name: "Zambia" },
  { code: "ZW", name: "Zimbabwe" }
];

/**
 * Returns a fallback list of countries with dial codes
 * Used when API is unavailable
 */
export function getFallbackCountries(): CountryWithDialCode[] {
  return ALL_COUNTRIES
    .map(country => ({
      code: country.code,
      name: country.name,
      dialCode: COUNTRY_TO_DIAL_CODE[country.code] || ''
    }))
    .filter(country => country.dialCode) // Only include countries with dial codes
    .sort((a, b) => a.name.localeCompare(b.name));
}

